project:
  output-dir: _outputs/html

website:
  announcement:
     content: |
        ![](resources/images/ants.png){.iasi-ants-image}
     position: above-navbar
     dismissable: false
    
book:
  page-footer:
    left: "© 2026 Javier G. Grandez"
    center: '<span id="iasi-publish-date"></span>'
    right:
      - text: "Licencias"
        href: 903-licenses.qmd

  sidebar:
     collapse-level: 1
    
  navbar:
    title: "IASI VOL. I"
    background: primary
    pinned: true

    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Introducción"
        href: chapters/11-intro/index.qmd
      - text: "Conceptos"
        href: chapters/12-conceptos/index.qmd
      - text: "Foundations"
        href: chapters/13-foundations/index.qmd
      - text: "Conceptos LLM"
        href: chapters/14-marco/index.qmd
      - text: "Metodologias"
        href: chapters/20-methodologies/index.qmd
      - text: "Componentes"
        href: chapters/30-components/index.qmd
      - text: "Saco"
        href: chapters/99-saco/index.qmd
        
    right:
      - icon: download 
        text: "Guardar ..."
        menu: 
           - text: "Guardar ..."
             href: "#iasi-exports"    
      - icon: box-arrow-up-right
        href: "#iasi-open-external"
        aria-label: "Abrir en una pestaña nueva"
        
  search:
    location: navbar
    type: overlay

format:
  html:
    pagetitle: "IASI Vol. I"
    title-prefix: ""
    include-in-header:
      text: '<script src="resources/js/iasi.js"></script>'
    theme: 
      - cosmo
      - resources/css/iasi.scss
      - resources/css/book.scss
    toc: true
