project:
  output-dir: outputs/docs/html

website:
  announcement:
    content: |
      ![](images/ants.png){.iasi-ants-image}
    position: above-navbar
    dismissable: false

book:
  llms-txt: true

  page-footer:
    left: "© 2026 Javier G. Grandez · IASI Rocks 🤘"
    center: '<span id="iasi-publish-date"></span>'
    right:
      - text: "Licencias"
        href: 903-licenses.qmd

  sidebar:
    collapse-level: 1

  navbar:
    title: "IASI VOL. I"
    background: primary
    pinned: true

    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Introducción"
        href: chapters/10-part-I/01-intro/index.qmd
      - text: "Fundamentos"
        menu:
          - text: "Introducción"
            href: "chapters/10-part-I/01-intro/index.qmd"
          - text: "Conceptos"
            href: "chapters/10-part-I/02-conceptos/index.qmd"
          - text: "Foundations"
            href: "chapters/10-part-I/03-foundations/index.qmd"
      - text: "Ingenieria"
        menu:
          - text: "Organizacion"
            href: "chapters/20-part-II/01-organization/index.qmd"
          - text: "Ingenieria"
            href: "chapters/20-part-II/02-engineering/index.qmd"
          - text: "Metodologias"
            href: "chapters/20-part-II/03-methodologies/index.qmd"
      - text: "SSII"
        menu:
          - text: "Marco"
            href: "chapters/30-part-III/01-marco/index.qmd"
          - text: "Componentes"
            href: "chapters/30-part-III/02-components/index.qmd"

    right:
      - icon: download
        text: "Guardar ..."
        menu:
          - text: "Guardar ..."
            href: "#iasi-exports"

      - icon: box-arrow-up-right
        href: "#iasi-open-external"
        aria-label: "Abrir en una pestaña nueva"

  search:
    location: navbar
    type: overlay

format:
  html:
    pagetitle: "IASI Vol. I"
    title-prefix: ""

    theme:
      - cosmo
      - resources/css/iasi.scss
      - resources/css/book.scss

    toc: true
