project:
  type: book

  resources:
    - LICENSES/*.txt
    
profile:
  group:
    - [html, pdf]

metadata-files:
  - _book-structure.yml

lang: es

bibliography:
   - references/historia-ia.bib
   - references/inteligencia-artificial.bib
   - references/historia-software.bib
   - references/ingenieria-software.bib          


book:
  title: "Ingeniería asistida por sistemas inteligentes"
  author: "Javier G. Grandez"
  output-file: "iasi"

  page-footer:
    left: "© 2026 Javier G. Grandez"
    right:
      - text: "Licencias"
        href: licenses.qmd
  navbar:
    title: "IASI"
    background: primary
    pinned: true

    left:
      - text: "Inicio"
        href: index.qmd

      - text: "Introducción"
        href: chapters/10-intro/index.qmd

      - text: "Conceptos"
        href: chapters/11-conceptos/index.qmd

      - text: "Foundations"
        href: chapters/12-foundations/index.qmd
        
      - text: "Conceptos LLM"
        href: chapters/13-foundations/index.qmd

      - text: "Saco"
        href: chapters/99-saco/index.qmd

  search:
    location: navbar
    type: overlay

copyright:
  holder: "Javier G. Grandez"
  year: 2026

license: "CC BY"

filters:
  - iasi-plantuml

filter-options:
  plantuml:
    enabled: true
    server: http://javier:1025
    cache: true
    styles:
      - resources/plantuml/iasi.puml
      
