project:
  type: book

  resources:
    - LICENSES/*.txt

profile:
  group:
    - [html, pdf]

metadata-files:
  - _book-structure.yml

lang: es

bibliography:
  - references/historia-ia.bib
  - references/inteligencia-artificial.bib
  - references/historia-software.bib
  - references/ingenieria-software.bib

book:
  title: "Ingeniería asistida por sistemas inteligentes"
  author: "Javier G. Grandez"
  output-file: "iasi-book-I"

copyright:
  holder: "Javier G. Grandez"
  year: 2026

license: "CC BY"

filters:
  - iasi-plantuml

filter-options:
  plantuml:
    enabled: true
    server: http://localhost:10025
    cache: true
    styles:
      - resources/plantuml/iasi.puml
